export const problemData = [{
        titleEn: 'What is Super Wind?',
        titleZh: '什么是风能？',
        contentEn: 'Super Wind is the conversion of the kinetic energy of wind into electrical energy. Wind energy is a clean and pollution-free renewable energy source. It has been used by people for a long time, mainly through windmills to pump water and grind noodles. People are interested in how to use wind to generate electricity.',
        contentZh: '风能是将风的动能转化为电能。风能是一种清洁、无污染的可再生能源。人们长期以来一直使用它，主要是通过风车来抽水和磨面。人们对如何利用风发电感兴趣。',
        titleId: 'Apa itu tenaga angin?',
        contentId: 'Tenaga angin adalah konversi energi kinetik angin menjadi energi listrik. Energi angin merupakan sumber energi terbarukan yang bersih dan bebas polusi. Ini telah digunakan oleh orang untuk waktu yang lama, terutama melalui kincir angin untuk memompa air dan menggiling mie. Orang-orang tertarik pada bagaimana menggunakan angin untuk menghasilkan listrik.',
        isOpen: false,
    },
    {
        titleEn: 'How to get fragments?',
        contentEn: 'Collect pieces to make animals, users can get pieces through quests, gifts from friends and lotteries.',
        titleZh: '风力发电原理?',
        contentZh: '将风的动能转化为机械动能，再将机械能转化为电能，这就是风力发电。风力发电的原理是利用风带动风车的叶片旋转，然后通过增压器提高转速，带动发电机发电。根据风车技术，在风速约每秒三米（风度）的情况下，就可以通电了。风力发电正在世界范围内形成热潮，因为风力发电不使用燃料，也不产生辐射或空气污染.',
        titleId: 'Prinsip pembangkit listrik tenaga angin?',
        contentId: 'Mengubah energi kinetik angin menjadi energi kinetik mekanik, dan kemudian mengubah energi mekanik menjadi energi kinetik listrik, inilah pembangkit listrik tenaga angin. Prinsip pembangkit tenaga angin adalah menggunakan angin untuk menggerakkan bilah kincir angin untuk berputar, dan kemudian meningkatkan kecepatan putaran melalui penambah kecepatan untuk mendorong generator menghasilkan listrik. Menurut teknologi kincir angin, pada kecepatan angin sekitar tiga meter per detik (derajat angin), listrik dapat dinyalakan. Tenaga angin sedang membentuk booming di dunia, karena tenaga angin tidak menggunakan bahan bakar, dan tidak menghasilkan radiasi atau polusi udara.',
        isOpen: false,
    },
    {
        titleEn: 'What are tradable items?',
        contentEn: 'Pets purchased through Flash sales can be sold or purchased in the Marketplace.',
        titleZh: '什么是可交易物品?',
        contentZh: '通过Flash sales抢购的宠物可在交易市场中出售，或者购买',
        titleId: 'Energi terbarukan untuk tenaga angin?',
        contentId: ' Penggunaan turbin angin berarti untuk terus mengubah energi angin menjadi listrik komersial standar yang digunakan oleh rumah kita.Karena kemajuan teknologi dan penggunaan pengisi daya dan inverter canggih, pembangkit listrik tenaga angin telah menjadi sistem kecil dengan kandungan teknologi tertentu dan dapat digunakan dalam Mengganti daya listrik normal dalam kondisi tertentu. Daerah pegunungan dapat menggunakan sistem untuk membuat lampu jalan yang tidak membutuhkan biaya sepanjang tahun; jalan raya dapat digunakan sebagai rambu jalan di malam hari; anak-anak di daerah pegunungan dapat belajar di malam hari di bawah lampu neon; motor angin juga dapat digunakan di atap gedung-gedung tinggi kecil di kota-kota, yang tidak hanya ekonomis tetapi juga benar-benar Green power.',
        isOpen: false,
    },
    {
        titleEn: 'Time and frequency?',
        contentEn: 'Three times in the morning, afternoon and evening, 9 sessions per day.',
        titleZh: '风电前景?',
        contentZh: '新能源战略开始聚焦大力发展风电。根据国家规划，未来15年全国风电装机容量将达到20～3000万千瓦。按照每千瓦装机容量7000元的设备投资计算，根据《风能世界》杂志的刊物，未来风电设备市场规模将高达1400亿元至2100亿元。',
        titleId: ' Prospek tenaga angin?',
        contentId: 'Strategi energi baru mulai fokus pada pengembangan tenaga angin dengan penuh semangat. Menurut rencana nasional, kapasitas terpasang tenaga angin nasional akan mencapai 20 hingga 30 juta kilowatt dalam 15 tahun ke depan. Dihitung berdasarkan investasi peralatan sebesar 7.000 yuan per kilowatt kapasitas terpasang, menurut publikasi majalah "Wind Energy World", pasar peralatan tenaga angin masa depan akan setinggi 140 miliar hingga 210 miliar yuan.',
        isOpen: false,
    },
]